_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "./model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 11
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('fsod-valorant-4-train',)
  TEST: ('fsod-valorant-4-test',)
SOLVER:
  IMS_PER_BATCH: 10
  BASE_LR: 0.001
  STEPS: (5000,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 100
  WARMUP_ITERS: 20
OUTPUT_DIR: "./checkpoints"

TEST:
  EVAL_PERIOD: 20